### ISSUE TITLE
desgin login page

### ISSUE THREAD

**Issue by mr-exception** [mr-exception/sparow#18]
* a card with username and password and a login button
* there are buttons to login as google, github and twitter
* a link to register page
* a link to forget password page
* logo of sparwo (we don't have a logo for sparow, so just use a sample image)
* logo of the client application (use a sample image here too)

**Comment by simti** [comment]
![login page](https://user-images.githubusercontent.com/13396356/100478088-6b4e0100-30ff-11eb-9a59-0ce38cba939f.png)

**Comment by mr-exception** [comment]
it's good thank you
