### ISSUE TITLE
design register page

### ISSUE THREAD

**Issue by mr-exception** [mr-exception/sparow#19]
* a card with username (required), password (required), email (required) and phone number (required)
* buttons to register as google, github and twitter
* links to login page and forget password
* logo of sparow and client application (just use a sample image)

**Comment by simti** [comment]
![register page](https://user-images.githubusercontent.com/13396356/100478058-4ce80580-30ff-11eb-9df2-41f90635066b.png)

**Comment by simti** [comment]
@mr-exception we don't need client logo in this and login page.we need that in the next step (approve page) where user read what kind of access he will give us and click accept button.
somthing like this:
![image](https://user-images.githubusercontent.com/13396356/100496914-4a23f980-316d-11eb-8197-8eacba2d0501.png)
so I don't consider it in my design.

**Comment by simti** [comment]
if we do not have this step let me know

**Comment by mr-exception** [comment]
it's okay we can design it later
